//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Application user.
    /// </summary>
    // *** Start programmer edit section *** (ApplicationUser CustomAttributes)

    // *** End programmer edit section *** (ApplicationUser CustomAttributes)
    [AutoAltered()]
    [Caption("Application user")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ApplicationUserE", new string[] {
            "Name as \'Имя\'",
            "Login as \'Логин\'",
            "EMail as \'E mail\'",
            "Phone1 as \'Номер телефона 1\'",
            "Phone2 as \'Номер телефона 2\'",
            "Phone3 as \'Номер телефона 3\'",
            "Activated as \'Активен\'",
            "VK as \'VK\'",
            "Facebook as \'Facebook\'",
            "Twitter as \'Twitter\'",
            "Birthday as \'Дата рождения\'",
            "Gender as \'Пол\'",
            "Vip as \'VIP\'",
            "Karma as \'Карма\'"})]
    [View("ApplicationUserL", new string[] {
            "Name as \'Имя\'",
            "EMail as \'E mail\'",
            "Birthday as \'Дата рождения\'",
            "Gender as \'Пол\'",
            "Vip as \'VIP\'",
            "Karma as \'Карма\'",
            "Phone1",
            "VK",
            "Facebook",
            "Twitter",
            "Activated",
            "Phone2",
            "Phone3",
            "Login"}, Hidden=new string[] {
            "Phone1",
            "VK",
            "Facebook",
            "Twitter",
            "Activated",
            "Phone2",
            "Phone3",
            "Login"})]
    public class ApplicationUser : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fLogin;
        
        private string fEMail;
        
        private string fPhone1;
        
        private string fPhone2;
        
        private string fPhone3;
        
        private bool fActivated;
        
        private string fVK;
        
        private string fFacebook;
        
        private string fTwitter;
        
        private System.DateTime? fBirthday;
        
        private FlexberryEmberDemo.Gender fGender;
        
        private bool fVip;
        
        private decimal fKarma = 100m;
        
        // *** Start programmer edit section *** (ApplicationUser CustomMembers)

        // *** End programmer edit section *** (ApplicationUser CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Name CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Name Get start)

                // *** End programmer edit section *** (ApplicationUser.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ApplicationUser.Name Get end)

                // *** End programmer edit section *** (ApplicationUser.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Name Set start)

                // *** End programmer edit section *** (ApplicationUser.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ApplicationUser.Name Set end)

                // *** End programmer edit section *** (ApplicationUser.Name Set end)
            }
        }
        
        /// <summary>
        /// Login.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Login CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Login CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Login
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Login Get start)

                // *** End programmer edit section *** (ApplicationUser.Login Get start)
                string result = this.fLogin;
                // *** Start programmer edit section *** (ApplicationUser.Login Get end)

                // *** End programmer edit section *** (ApplicationUser.Login Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Login Set start)

                // *** End programmer edit section *** (ApplicationUser.Login Set start)
                this.fLogin = value;
                // *** Start programmer edit section *** (ApplicationUser.Login Set end)

                // *** End programmer edit section *** (ApplicationUser.Login Set end)
            }
        }
        
        /// <summary>
        /// EMail.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.EMail CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.EMail CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string EMail
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.EMail Get start)

                // *** End programmer edit section *** (ApplicationUser.EMail Get start)
                string result = this.fEMail;
                // *** Start programmer edit section *** (ApplicationUser.EMail Get end)

                // *** End programmer edit section *** (ApplicationUser.EMail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.EMail Set start)

                // *** End programmer edit section *** (ApplicationUser.EMail Set start)
                this.fEMail = value;
                // *** Start programmer edit section *** (ApplicationUser.EMail Set end)

                // *** End programmer edit section *** (ApplicationUser.EMail Set end)
            }
        }
        
        /// <summary>
        /// Phone1.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Phone1 CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Phone1 CustomAttributes)
        [StrLen(255)]
        public virtual string Phone1
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Phone1 Get start)

                // *** End programmer edit section *** (ApplicationUser.Phone1 Get start)
                string result = this.fPhone1;
                // *** Start programmer edit section *** (ApplicationUser.Phone1 Get end)

                // *** End programmer edit section *** (ApplicationUser.Phone1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Phone1 Set start)

                // *** End programmer edit section *** (ApplicationUser.Phone1 Set start)
                this.fPhone1 = value;
                // *** Start programmer edit section *** (ApplicationUser.Phone1 Set end)

                // *** End programmer edit section *** (ApplicationUser.Phone1 Set end)
            }
        }
        
        /// <summary>
        /// Phone2.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Phone2 CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Phone2 CustomAttributes)
        [StrLen(255)]
        public virtual string Phone2
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Phone2 Get start)

                // *** End programmer edit section *** (ApplicationUser.Phone2 Get start)
                string result = this.fPhone2;
                // *** Start programmer edit section *** (ApplicationUser.Phone2 Get end)

                // *** End programmer edit section *** (ApplicationUser.Phone2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Phone2 Set start)

                // *** End programmer edit section *** (ApplicationUser.Phone2 Set start)
                this.fPhone2 = value;
                // *** Start programmer edit section *** (ApplicationUser.Phone2 Set end)

                // *** End programmer edit section *** (ApplicationUser.Phone2 Set end)
            }
        }
        
        /// <summary>
        /// Phone3.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Phone3 CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Phone3 CustomAttributes)
        [StrLen(255)]
        public virtual string Phone3
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Phone3 Get start)

                // *** End programmer edit section *** (ApplicationUser.Phone3 Get start)
                string result = this.fPhone3;
                // *** Start programmer edit section *** (ApplicationUser.Phone3 Get end)

                // *** End programmer edit section *** (ApplicationUser.Phone3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Phone3 Set start)

                // *** End programmer edit section *** (ApplicationUser.Phone3 Set start)
                this.fPhone3 = value;
                // *** Start programmer edit section *** (ApplicationUser.Phone3 Set end)

                // *** End programmer edit section *** (ApplicationUser.Phone3 Set end)
            }
        }
        
        /// <summary>
        /// Activated.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Activated CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Activated CustomAttributes)
        public virtual bool Activated
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Activated Get start)

                // *** End programmer edit section *** (ApplicationUser.Activated Get start)
                bool result = this.fActivated;
                // *** Start programmer edit section *** (ApplicationUser.Activated Get end)

                // *** End programmer edit section *** (ApplicationUser.Activated Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Activated Set start)

                // *** End programmer edit section *** (ApplicationUser.Activated Set start)
                this.fActivated = value;
                // *** Start programmer edit section *** (ApplicationUser.Activated Set end)

                // *** End programmer edit section *** (ApplicationUser.Activated Set end)
            }
        }
        
        /// <summary>
        /// VK.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.VK CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.VK CustomAttributes)
        [StrLen(255)]
        public virtual string VK
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.VK Get start)

                // *** End programmer edit section *** (ApplicationUser.VK Get start)
                string result = this.fVK;
                // *** Start programmer edit section *** (ApplicationUser.VK Get end)

                // *** End programmer edit section *** (ApplicationUser.VK Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.VK Set start)

                // *** End programmer edit section *** (ApplicationUser.VK Set start)
                this.fVK = value;
                // *** Start programmer edit section *** (ApplicationUser.VK Set end)

                // *** End programmer edit section *** (ApplicationUser.VK Set end)
            }
        }
        
        /// <summary>
        /// Facebook.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Facebook CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Facebook CustomAttributes)
        [StrLen(255)]
        public virtual string Facebook
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Facebook Get start)

                // *** End programmer edit section *** (ApplicationUser.Facebook Get start)
                string result = this.fFacebook;
                // *** Start programmer edit section *** (ApplicationUser.Facebook Get end)

                // *** End programmer edit section *** (ApplicationUser.Facebook Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Facebook Set start)

                // *** End programmer edit section *** (ApplicationUser.Facebook Set start)
                this.fFacebook = value;
                // *** Start programmer edit section *** (ApplicationUser.Facebook Set end)

                // *** End programmer edit section *** (ApplicationUser.Facebook Set end)
            }
        }
        
        /// <summary>
        /// Twitter.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Twitter CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Twitter CustomAttributes)
        [StrLen(255)]
        public virtual string Twitter
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Twitter Get start)

                // *** End programmer edit section *** (ApplicationUser.Twitter Get start)
                string result = this.fTwitter;
                // *** Start programmer edit section *** (ApplicationUser.Twitter Get end)

                // *** End programmer edit section *** (ApplicationUser.Twitter Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Twitter Set start)

                // *** End programmer edit section *** (ApplicationUser.Twitter Set start)
                this.fTwitter = value;
                // *** Start programmer edit section *** (ApplicationUser.Twitter Set end)

                // *** End programmer edit section *** (ApplicationUser.Twitter Set end)
            }
        }
        
        /// <summary>
        /// Birthday.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Birthday CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Birthday CustomAttributes)
        public virtual System.DateTime? Birthday
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Birthday Get start)

                // *** End programmer edit section *** (ApplicationUser.Birthday Get start)
                System.DateTime? result = this.fBirthday;
                // *** Start programmer edit section *** (ApplicationUser.Birthday Get end)

                // *** End programmer edit section *** (ApplicationUser.Birthday Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Birthday Set start)

                // *** End programmer edit section *** (ApplicationUser.Birthday Set start)
                this.fBirthday = value;
                // *** Start programmer edit section *** (ApplicationUser.Birthday Set end)

                // *** End programmer edit section *** (ApplicationUser.Birthday Set end)
            }
        }
        
        /// <summary>
        /// Gender.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Gender CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Gender CustomAttributes)
        public virtual FlexberryEmberDemo.Gender Gender
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Gender Get start)

                // *** End programmer edit section *** (ApplicationUser.Gender Get start)
                FlexberryEmberDemo.Gender result = this.fGender;
                // *** Start programmer edit section *** (ApplicationUser.Gender Get end)

                // *** End programmer edit section *** (ApplicationUser.Gender Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Gender Set start)

                // *** End programmer edit section *** (ApplicationUser.Gender Set start)
                this.fGender = value;
                // *** Start programmer edit section *** (ApplicationUser.Gender Set end)

                // *** End programmer edit section *** (ApplicationUser.Gender Set end)
            }
        }
        
        /// <summary>
        /// Vip.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Vip CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Vip CustomAttributes)
        public virtual bool Vip
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Vip Get start)

                // *** End programmer edit section *** (ApplicationUser.Vip Get start)
                bool result = this.fVip;
                // *** Start programmer edit section *** (ApplicationUser.Vip Get end)

                // *** End programmer edit section *** (ApplicationUser.Vip Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Vip Set start)

                // *** End programmer edit section *** (ApplicationUser.Vip Set start)
                this.fVip = value;
                // *** Start programmer edit section *** (ApplicationUser.Vip Set end)

                // *** End programmer edit section *** (ApplicationUser.Vip Set end)
            }
        }
        
        /// <summary>
        /// Karma.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationUser.Karma CustomAttributes)

        // *** End programmer edit section *** (ApplicationUser.Karma CustomAttributes)
        public virtual decimal Karma
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationUser.Karma Get start)

                // *** End programmer edit section *** (ApplicationUser.Karma Get start)
                decimal result = this.fKarma;
                // *** Start programmer edit section *** (ApplicationUser.Karma Get end)

                // *** End programmer edit section *** (ApplicationUser.Karma Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationUser.Karma Set start)

                // *** End programmer edit section *** (ApplicationUser.Karma Set start)
                this.fKarma = value;
                // *** Start programmer edit section *** (ApplicationUser.Karma Set end)

                // *** End programmer edit section *** (ApplicationUser.Karma Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ApplicationUserE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationUserE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationUserE", typeof(FlexberryEmberDemo.ApplicationUser));
                }
            }
            
            /// <summary>
            /// "ApplicationUserL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationUserL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationUserL", typeof(FlexberryEmberDemo.ApplicationUser));
                }
            }
        }
    }
}
