//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Comment vote.
    /// </summary>
    // *** Start programmer edit section *** (CommentVote CustomAttributes)

    // *** End programmer edit section *** (CommentVote CustomAttributes)
    [AutoAltered()]
    [Caption("Comment vote")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CommentVoteE", new string[] {
            "VoteType as \'Тип голосования\'",
            "ApplicationUser as \'Пользователь приложения\'",
            "ApplicationUser.Name as \'Name\'"}, Hidden=new string[] {
            "ApplicationUser.Name"})]
    [MasterViewDefineAttribute("CommentVoteE", "ApplicationUser", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class CommentVote : ICSSoft.STORMNET.DataObject
    {
        
        private FlexberryEmberDemo.VoteType fVoteType;
        
        private FlexberryEmberDemo.ApplicationUser fApplicationUser;
        
        private FlexberryEmberDemo.Comment fComment;
        
        // *** Start programmer edit section *** (CommentVote CustomMembers)

        // *** End programmer edit section *** (CommentVote CustomMembers)

        
        /// <summary>
        /// VoteType.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.VoteType CustomAttributes)

        // *** End programmer edit section *** (CommentVote.VoteType CustomAttributes)
        public virtual FlexberryEmberDemo.VoteType VoteType
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.VoteType Get start)

                // *** End programmer edit section *** (CommentVote.VoteType Get start)
                FlexberryEmberDemo.VoteType result = this.fVoteType;
                // *** Start programmer edit section *** (CommentVote.VoteType Get end)

                // *** End programmer edit section *** (CommentVote.VoteType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.VoteType Set start)

                // *** End programmer edit section *** (CommentVote.VoteType Set start)
                this.fVoteType = value;
                // *** Start programmer edit section *** (CommentVote.VoteType Set end)

                // *** End programmer edit section *** (CommentVote.VoteType Set end)
            }
        }
        
        /// <summary>
        /// Comment vote.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.ApplicationUser CustomAttributes)

        // *** End programmer edit section *** (CommentVote.ApplicationUser CustomAttributes)
        [PropertyStorage(new string[] {
                "ApplicationUser"})]
        [NotNull()]
        public virtual FlexberryEmberDemo.ApplicationUser ApplicationUser
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.ApplicationUser Get start)

                // *** End programmer edit section *** (CommentVote.ApplicationUser Get start)
                FlexberryEmberDemo.ApplicationUser result = this.fApplicationUser;
                // *** Start programmer edit section *** (CommentVote.ApplicationUser Get end)

                // *** End programmer edit section *** (CommentVote.ApplicationUser Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.ApplicationUser Set start)

                // *** End programmer edit section *** (CommentVote.ApplicationUser Set start)
                this.fApplicationUser = value;
                // *** Start programmer edit section *** (CommentVote.ApplicationUser Set end)

                // *** End programmer edit section *** (CommentVote.ApplicationUser Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку FlexberryEmberDemo.Comment.
        /// </summary>
        // *** Start programmer edit section *** (CommentVote.Comment CustomAttributes)

        // *** End programmer edit section *** (CommentVote.Comment CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Comment"})]
        public virtual FlexberryEmberDemo.Comment Comment
        {
            get
            {
                // *** Start programmer edit section *** (CommentVote.Comment Get start)

                // *** End programmer edit section *** (CommentVote.Comment Get start)
                FlexberryEmberDemo.Comment result = this.fComment;
                // *** Start programmer edit section *** (CommentVote.Comment Get end)

                // *** End programmer edit section *** (CommentVote.Comment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CommentVote.Comment Set start)

                // *** End programmer edit section *** (CommentVote.Comment Set start)
                this.fComment = value;
                // *** Start programmer edit section *** (CommentVote.Comment Set end)

                // *** End programmer edit section *** (CommentVote.Comment Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CommentVoteE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CommentVoteE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CommentVoteE", typeof(FlexberryEmberDemo.CommentVote));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of CommentVote.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfCommentVote CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfCommentVote CustomAttributes)
    public class DetailArrayOfCommentVote : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (FlexberryEmberDemo.DetailArrayOfCommentVote members)

        // *** End programmer edit section *** (FlexberryEmberDemo.DetailArrayOfCommentVote members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type CommentVote by index.
        /// </summary>
        /// <summary>
        /// Adds object with type CommentVote.
        /// </summary>
        public DetailArrayOfCommentVote(FlexberryEmberDemo.Comment fComment) : 
                base(typeof(CommentVote), ((ICSSoft.STORMNET.DataObject)(fComment)))
        {
        }
        
        public FlexberryEmberDemo.CommentVote this[int index]
        {
            get
            {
                return ((FlexberryEmberDemo.CommentVote)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(FlexberryEmberDemo.CommentVote dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
