//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Comment.
    /// </summary>
    // *** Start programmer edit section *** (Comment CustomAttributes)

    // *** End programmer edit section *** (Comment CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CommentE", new string[] {
            "Text as \'Текст\'",
            "Votes as \'Голоса\'",
            "Moderated as \'Одобрен\'",
            "Author as \'Автор\'",
            "Author.Name as \'Name\'"}, Hidden=new string[] {
            "Author.Name"})]
    [AssociatedDetailViewAttribute("CommentE", "UserVotes", "CommentVoteE", true, "", "Голоса пользователей", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("CommentE", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Comment : ICSSoft.STORMNET.DataObject
    {
        
        private string fText;
        
        private long fVotes;
        
        private bool fModerated;
        
        private FlexberryEmberDemo.ApplicationUser fAuthor;
        
        private FlexberryEmberDemo.DetailArrayOfCommentVote fUserVotes;
        
        private FlexberryEmberDemo.Suggestion fSuggestion;
        
        // *** Start programmer edit section *** (Comment CustomMembers)

        // *** End programmer edit section *** (Comment CustomMembers)

        
        /// <summary>
        /// Text.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Text CustomAttributes)

        // *** End programmer edit section *** (Comment.Text CustomAttributes)
        [StrLen(255)]
        public virtual string Text
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Text Get start)

                // *** End programmer edit section *** (Comment.Text Get start)
                string result = this.fText;
                // *** Start programmer edit section *** (Comment.Text Get end)

                // *** End programmer edit section *** (Comment.Text Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Text Set start)

                // *** End programmer edit section *** (Comment.Text Set start)
                this.fText = value;
                // *** Start programmer edit section *** (Comment.Text Set end)

                // *** End programmer edit section *** (Comment.Text Set end)
            }
        }
        
        /// <summary>
        /// Votes.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Votes CustomAttributes)

        // *** End programmer edit section *** (Comment.Votes CustomAttributes)
        public virtual long Votes
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Votes Get start)

                // *** End programmer edit section *** (Comment.Votes Get start)
                long result = this.fVotes;
                // *** Start programmer edit section *** (Comment.Votes Get end)

                // *** End programmer edit section *** (Comment.Votes Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Votes Set start)

                // *** End programmer edit section *** (Comment.Votes Set start)
                this.fVotes = value;
                // *** Start programmer edit section *** (Comment.Votes Set end)

                // *** End programmer edit section *** (Comment.Votes Set end)
            }
        }
        
        /// <summary>
        /// Moderated.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Moderated CustomAttributes)

        // *** End programmer edit section *** (Comment.Moderated CustomAttributes)
        public virtual bool Moderated
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Moderated Get start)

                // *** End programmer edit section *** (Comment.Moderated Get start)
                bool result = this.fModerated;
                // *** Start programmer edit section *** (Comment.Moderated Get end)

                // *** End programmer edit section *** (Comment.Moderated Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Moderated Set start)

                // *** End programmer edit section *** (Comment.Moderated Set start)
                this.fModerated = value;
                // *** Start programmer edit section *** (Comment.Moderated Set end)

                // *** End programmer edit section *** (Comment.Moderated Set end)
            }
        }
        
        /// <summary>
        /// Comment.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Author CustomAttributes)

        // *** End programmer edit section *** (Comment.Author CustomAttributes)
        [PropertyStorage(new string[] {
                "Author"})]
        [NotNull()]
        public virtual FlexberryEmberDemo.ApplicationUser Author
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Author Get start)

                // *** End programmer edit section *** (Comment.Author Get start)
                FlexberryEmberDemo.ApplicationUser result = this.fAuthor;
                // *** Start programmer edit section *** (Comment.Author Get end)

                // *** End programmer edit section *** (Comment.Author Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Author Set start)

                // *** End programmer edit section *** (Comment.Author Set start)
                this.fAuthor = value;
                // *** Start programmer edit section *** (Comment.Author Set end)

                // *** End programmer edit section *** (Comment.Author Set end)
            }
        }
        
        /// <summary>
        /// Comment.
        /// </summary>
        // *** Start programmer edit section *** (Comment.UserVotes CustomAttributes)

        // *** End programmer edit section *** (Comment.UserVotes CustomAttributes)
        public virtual FlexberryEmberDemo.DetailArrayOfCommentVote UserVotes
        {
            get
            {
                // *** Start programmer edit section *** (Comment.UserVotes Get start)

                // *** End programmer edit section *** (Comment.UserVotes Get start)
                if ((this.fUserVotes == null))
                {
                    this.fUserVotes = new FlexberryEmberDemo.DetailArrayOfCommentVote(this);
                }
                FlexberryEmberDemo.DetailArrayOfCommentVote result = this.fUserVotes;
                // *** Start programmer edit section *** (Comment.UserVotes Get end)

                // *** End programmer edit section *** (Comment.UserVotes Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.UserVotes Set start)

                // *** End programmer edit section *** (Comment.UserVotes Set start)
                this.fUserVotes = value;
                // *** Start programmer edit section *** (Comment.UserVotes Set end)

                // *** End programmer edit section *** (Comment.UserVotes Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку FlexberryEmberDemo.Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Suggestion CustomAttributes)

        // *** End programmer edit section *** (Comment.Suggestion CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Suggestion"})]
        public virtual FlexberryEmberDemo.Suggestion Suggestion
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Suggestion Get start)

                // *** End programmer edit section *** (Comment.Suggestion Get start)
                FlexberryEmberDemo.Suggestion result = this.fSuggestion;
                // *** Start programmer edit section *** (Comment.Suggestion Get end)

                // *** End programmer edit section *** (Comment.Suggestion Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Suggestion Set start)

                // *** End programmer edit section *** (Comment.Suggestion Set start)
                this.fSuggestion = value;
                // *** Start programmer edit section *** (Comment.Suggestion Set end)

                // *** End programmer edit section *** (Comment.Suggestion Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CommentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CommentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CommentE", typeof(FlexberryEmberDemo.Comment));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Comment.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfComment CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfComment CustomAttributes)
    public class DetailArrayOfComment : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (FlexberryEmberDemo.DetailArrayOfComment members)

        // *** End programmer edit section *** (FlexberryEmberDemo.DetailArrayOfComment members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Comment by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Comment.
        /// </summary>
        public DetailArrayOfComment(FlexberryEmberDemo.Suggestion fSuggestion) : 
                base(typeof(Comment), ((ICSSoft.STORMNET.DataObject)(fSuggestion)))
        {
        }
        
        public FlexberryEmberDemo.Comment this[int index]
        {
            get
            {
                return ((FlexberryEmberDemo.Comment)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(FlexberryEmberDemo.Comment dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
