//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Localization.
    /// </summary>
    // *** Start programmer edit section *** (Localization CustomAttributes)

    // *** End programmer edit section *** (Localization CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LocalizationE", new string[] {
            "Name as \'Название\'"})]
    [View("LocalizationL", new string[] {
            "Name as \'Название\'"})]
    public class Localization : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Localization CustomMembers)

        // *** End programmer edit section *** (Localization CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Localization.Name CustomAttributes)

        // *** End programmer edit section *** (Localization.Name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Localization.Name Get start)

                // *** End programmer edit section *** (Localization.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Localization.Name Get end)

                // *** End programmer edit section *** (Localization.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Localization.Name Set start)

                // *** End programmer edit section *** (Localization.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Localization.Name Set end)

                // *** End programmer edit section *** (Localization.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LocalizationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LocalizationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LocalizationE", typeof(FlexberryEmberDemo.Localization));
                }
            }
            
            /// <summary>
            /// "LocalizationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LocalizationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LocalizationL", typeof(FlexberryEmberDemo.Localization));
                }
            }
        }
    }
}
