//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Localized suggestion type.
    /// </summary>
    // *** Start programmer edit section *** (LocalizedSuggestionType CustomAttributes)

    // *** End programmer edit section *** (LocalizedSuggestionType CustomAttributes)
    [AutoAltered()]
    [Caption("Localized suggestion type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LocalizedSuggestionTypeE", new string[] {
            "Name as \'Название\'",
            "Localization as \'Локализация\'",
            "Localization.Name as \'Name\'"}, Hidden=new string[] {
            "Localization.Name"})]
    [MasterViewDefineAttribute("LocalizedSuggestionTypeE", "Localization", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class LocalizedSuggestionType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private FlexberryEmberDemo.Localization fLocalization;
        
        private FlexberryEmberDemo.SuggestionType fSuggestionType;
        
        // *** Start programmer edit section *** (LocalizedSuggestionType CustomMembers)

        // *** End programmer edit section *** (LocalizedSuggestionType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.Name CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.Name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Name Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Name Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Name Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Name Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Name Set end)
            }
        }
        
        /// <summary>
        /// Localized suggestion type.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.Localization CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.Localization CustomAttributes)
        [PropertyStorage(new string[] {
                "Localization"})]
        [NotNull()]
        public virtual FlexberryEmberDemo.Localization Localization
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Localization Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Localization Get start)
                FlexberryEmberDemo.Localization result = this.fLocalization;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Localization Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Localization Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.Localization Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.Localization Set start)
                this.fLocalization = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.Localization Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.Localization Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку FlexberryEmberDemo.SuggestionType.
        /// </summary>
        // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType CustomAttributes)

        // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "SuggestionType"})]
        public virtual FlexberryEmberDemo.SuggestionType SuggestionType
        {
            get
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType Get start)

                // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType Get start)
                FlexberryEmberDemo.SuggestionType result = this.fSuggestionType;
                // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType Get end)

                // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType Set start)

                // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType Set start)
                this.fSuggestionType = value;
                // *** Start programmer edit section *** (LocalizedSuggestionType.SuggestionType Set end)

                // *** End programmer edit section *** (LocalizedSuggestionType.SuggestionType Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LocalizedSuggestionTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LocalizedSuggestionTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LocalizedSuggestionTypeE", typeof(FlexberryEmberDemo.LocalizedSuggestionType));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of LocalizedSuggestionType.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLocalizedSuggestionType CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLocalizedSuggestionType CustomAttributes)
    public class DetailArrayOfLocalizedSuggestionType : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (FlexberryEmberDemo.DetailArrayOfLocalizedSuggestionType members)

        // *** End programmer edit section *** (FlexberryEmberDemo.DetailArrayOfLocalizedSuggestionType members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LocalizedSuggestionType by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LocalizedSuggestionType.
        /// </summary>
        public DetailArrayOfLocalizedSuggestionType(FlexberryEmberDemo.SuggestionType fSuggestionType) : 
                base(typeof(LocalizedSuggestionType), ((ICSSoft.STORMNET.DataObject)(fSuggestionType)))
        {
        }
        
        public FlexberryEmberDemo.LocalizedSuggestionType this[int index]
        {
            get
            {
                return ((FlexberryEmberDemo.LocalizedSuggestionType)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(FlexberryEmberDemo.LocalizedSuggestionType dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
