//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Offline user.
    /// </summary>
    // *** Start programmer edit section *** (OfflineUser CustomAttributes)

    // *** End programmer edit section *** (OfflineUser CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [Caption("Оффлайн пользователь")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("OfflineUserE", new string[] {
            "Login as \'Логин\'",
            "Password as \'Пароль\'"})]
    public class OfflineUser : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (OfflineUser CustomMembers)

        // *** End programmer edit section *** (OfflineUser CustomMembers)

        
        /// <summary>
        /// Login.
        /// </summary>
        // *** Start programmer edit section *** (OfflineUser.Login CustomAttributes)

        // *** End programmer edit section *** (OfflineUser.Login CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        public virtual string Login
        {
            get
            {
                // *** Start programmer edit section *** (OfflineUser.Login Get)

                return null;
                // *** End programmer edit section *** (OfflineUser.Login Get)
            }
            set
            {
                // *** Start programmer edit section *** (OfflineUser.Login Set)

                // *** End programmer edit section *** (OfflineUser.Login Set)
            }
        }
        
        /// <summary>
        /// Password.
        /// </summary>
        // *** Start programmer edit section *** (OfflineUser.Password CustomAttributes)

        // *** End programmer edit section *** (OfflineUser.Password CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        public virtual string Password
        {
            get
            {
                // *** Start programmer edit section *** (OfflineUser.Password Get)

                return null;
                // *** End programmer edit section *** (OfflineUser.Password Get)
            }
            set
            {
                // *** Start programmer edit section *** (OfflineUser.Password Set)

                // *** End programmer edit section *** (OfflineUser.Password Set)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "OfflineUserE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OfflineUserE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OfflineUserE", typeof(FlexberryEmberDemo.OfflineUser));
                }
            }
        }
    }
}
