//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Suggestion.
    /// </summary>
    // *** Start programmer edit section *** (Suggestion CustomAttributes)

    // *** End programmer edit section *** (Suggestion CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SuggestionE", new string[] {
            "Address as \'Адрес\'",
            "Text as \'Текст\'",
            "Polygon as \'Полигон\'",
            "Date as \'Дата\'",
            "Votes as \'Голоса\'",
            "Moderated as \'Одобрено\'",
            "Type as \'Тип\'",
            "Type.Name as \'Name\'",
            "Author as \'Автор\'",
            "Author.Name as \'Name\'"}, Hidden=new string[] {
            "Type.Name",
            "Author.Name"})]
    [AssociatedDetailViewAttribute("SuggestionE", "Comments", "CommentE", true, "", "Комментарии", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("SuggestionE", "Files", "SuggestionFileE", true, "", "Файлы", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("SuggestionE", "UserVotes", "VoteE", true, "", "Голоса пользователей", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("SuggestionE", "Type", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("SuggestionE", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("SuggestionL", new string[] {
            "Address as \'Адрес\'",
            "Text as \'Текст\'",
            "Date as \'Дата\'",
            "Votes as \'Голоса\'",
            "Moderated as \'Одобрено\'",
            "Type.Name as \'Тип предложения\'",
            "Author.Name as \'Автор\'",
            "Polygon"}, Hidden=new string[] {
            "Polygon"})]
    public class Suggestion : ICSSoft.STORMNET.DataObject
    {
        
        private string fAddress;
        
        private string fText;
        
        private System.DateTime fDate = System.DateTime.Now;
        
        private long fVotes;
        
        private bool fModerated;
        
        private string fPolygon;
        
        private FlexberryEmberDemo.SuggestionType fType;
        
        private FlexberryEmberDemo.ApplicationUser fAuthor;
        
        private FlexberryEmberDemo.DetailArrayOfComment fComments;
        
        private FlexberryEmberDemo.DetailArrayOfSuggestionFile fFiles;
        
        private FlexberryEmberDemo.DetailArrayOfVote fUserVotes;
        
        // *** Start programmer edit section *** (Suggestion CustomMembers)

        // *** End programmer edit section *** (Suggestion CustomMembers)

        
        /// <summary>
        /// Address.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Address CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Address Get start)

                // *** End programmer edit section *** (Suggestion.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (Suggestion.Address Get end)

                // *** End programmer edit section *** (Suggestion.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Address Set start)

                // *** End programmer edit section *** (Suggestion.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Suggestion.Address Set end)

                // *** End programmer edit section *** (Suggestion.Address Set end)
            }
        }
        
        /// <summary>
        /// Text.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Text CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Text CustomAttributes)
        [StrLen(255)]
        public virtual string Text
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Text Get start)

                // *** End programmer edit section *** (Suggestion.Text Get start)
                string result = this.fText;
                // *** Start programmer edit section *** (Suggestion.Text Get end)

                // *** End programmer edit section *** (Suggestion.Text Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Text Set start)

                // *** End programmer edit section *** (Suggestion.Text Set start)
                this.fText = value;
                // *** Start programmer edit section *** (Suggestion.Text Set end)

                // *** End programmer edit section *** (Suggestion.Text Set end)
            }
        }
        
        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Date CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Date Get start)

                // *** End programmer edit section *** (Suggestion.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (Suggestion.Date Get end)

                // *** End programmer edit section *** (Suggestion.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Date Set start)

                // *** End programmer edit section *** (Suggestion.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (Suggestion.Date Set end)

                // *** End programmer edit section *** (Suggestion.Date Set end)
            }
        }
        
        /// <summary>
        /// Votes.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Votes CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Votes CustomAttributes)
        public virtual long Votes
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Votes Get start)

                // *** End programmer edit section *** (Suggestion.Votes Get start)
                long result = this.fVotes;
                // *** Start programmer edit section *** (Suggestion.Votes Get end)

                // *** End programmer edit section *** (Suggestion.Votes Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Votes Set start)

                // *** End programmer edit section *** (Suggestion.Votes Set start)
                this.fVotes = value;
                // *** Start programmer edit section *** (Suggestion.Votes Set end)

                // *** End programmer edit section *** (Suggestion.Votes Set end)
            }
        }
        
        /// <summary>
        /// Moderated.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Moderated CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Moderated CustomAttributes)
        public virtual bool Moderated
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Moderated Get start)

                // *** End programmer edit section *** (Suggestion.Moderated Get start)
                bool result = this.fModerated;
                // *** Start programmer edit section *** (Suggestion.Moderated Get end)

                // *** End programmer edit section *** (Suggestion.Moderated Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Moderated Set start)

                // *** End programmer edit section *** (Suggestion.Moderated Set start)
                this.fModerated = value;
                // *** Start programmer edit section *** (Suggestion.Moderated Set end)

                // *** End programmer edit section *** (Suggestion.Moderated Set end)
            }
        }
        
        /// <summary>
        /// Polygon.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Polygon CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Polygon CustomAttributes)
        public virtual string Polygon
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Polygon Get start)

                // *** End programmer edit section *** (Suggestion.Polygon Get start)
                string result = this.fPolygon;
                // *** Start programmer edit section *** (Suggestion.Polygon Get end)

                // *** End programmer edit section *** (Suggestion.Polygon Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Polygon Set start)

                // *** End programmer edit section *** (Suggestion.Polygon Set start)
                this.fPolygon = value;
                // *** Start programmer edit section *** (Suggestion.Polygon Set end)

                // *** End programmer edit section *** (Suggestion.Polygon Set end)
            }
        }
        
        /// <summary>
        /// Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Type CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Type CustomAttributes)
        [PropertyStorage(new string[] {
                "Type"})]
        [NotNull()]
        public virtual FlexberryEmberDemo.SuggestionType Type
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Type Get start)

                // *** End programmer edit section *** (Suggestion.Type Get start)
                FlexberryEmberDemo.SuggestionType result = this.fType;
                // *** Start programmer edit section *** (Suggestion.Type Get end)

                // *** End programmer edit section *** (Suggestion.Type Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Type Set start)

                // *** End programmer edit section *** (Suggestion.Type Set start)
                this.fType = value;
                // *** Start programmer edit section *** (Suggestion.Type Set end)

                // *** End programmer edit section *** (Suggestion.Type Set end)
            }
        }
        
        /// <summary>
        /// Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Author CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Author CustomAttributes)
        [PropertyStorage(new string[] {
                "Author"})]
        [NotNull()]
        public virtual FlexberryEmberDemo.ApplicationUser Author
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Author Get start)

                // *** End programmer edit section *** (Suggestion.Author Get start)
                FlexberryEmberDemo.ApplicationUser result = this.fAuthor;
                // *** Start programmer edit section *** (Suggestion.Author Get end)

                // *** End programmer edit section *** (Suggestion.Author Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Author Set start)

                // *** End programmer edit section *** (Suggestion.Author Set start)
                this.fAuthor = value;
                // *** Start programmer edit section *** (Suggestion.Author Set end)

                // *** End programmer edit section *** (Suggestion.Author Set end)
            }
        }
        
        /// <summary>
        /// Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Comments CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Comments CustomAttributes)
        public virtual FlexberryEmberDemo.DetailArrayOfComment Comments
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Comments Get start)

                // *** End programmer edit section *** (Suggestion.Comments Get start)
                if ((this.fComments == null))
                {
                    this.fComments = new FlexberryEmberDemo.DetailArrayOfComment(this);
                }
                FlexberryEmberDemo.DetailArrayOfComment result = this.fComments;
                // *** Start programmer edit section *** (Suggestion.Comments Get end)

                // *** End programmer edit section *** (Suggestion.Comments Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Comments Set start)

                // *** End programmer edit section *** (Suggestion.Comments Set start)
                this.fComments = value;
                // *** Start programmer edit section *** (Suggestion.Comments Set end)

                // *** End programmer edit section *** (Suggestion.Comments Set end)
            }
        }
        
        /// <summary>
        /// Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.Files CustomAttributes)

        // *** End programmer edit section *** (Suggestion.Files CustomAttributes)
        public virtual FlexberryEmberDemo.DetailArrayOfSuggestionFile Files
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.Files Get start)

                // *** End programmer edit section *** (Suggestion.Files Get start)
                if ((this.fFiles == null))
                {
                    this.fFiles = new FlexberryEmberDemo.DetailArrayOfSuggestionFile(this);
                }
                FlexberryEmberDemo.DetailArrayOfSuggestionFile result = this.fFiles;
                // *** Start programmer edit section *** (Suggestion.Files Get end)

                // *** End programmer edit section *** (Suggestion.Files Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.Files Set start)

                // *** End programmer edit section *** (Suggestion.Files Set start)
                this.fFiles = value;
                // *** Start programmer edit section *** (Suggestion.Files Set end)

                // *** End programmer edit section *** (Suggestion.Files Set end)
            }
        }
        
        /// <summary>
        /// Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Suggestion.UserVotes CustomAttributes)

        // *** End programmer edit section *** (Suggestion.UserVotes CustomAttributes)
        public virtual FlexberryEmberDemo.DetailArrayOfVote UserVotes
        {
            get
            {
                // *** Start programmer edit section *** (Suggestion.UserVotes Get start)

                // *** End programmer edit section *** (Suggestion.UserVotes Get start)
                if ((this.fUserVotes == null))
                {
                    this.fUserVotes = new FlexberryEmberDemo.DetailArrayOfVote(this);
                }
                FlexberryEmberDemo.DetailArrayOfVote result = this.fUserVotes;
                // *** Start programmer edit section *** (Suggestion.UserVotes Get end)

                // *** End programmer edit section *** (Suggestion.UserVotes Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Suggestion.UserVotes Set start)

                // *** End programmer edit section *** (Suggestion.UserVotes Set start)
                this.fUserVotes = value;
                // *** Start programmer edit section *** (Suggestion.UserVotes Set end)

                // *** End programmer edit section *** (Suggestion.UserVotes Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SuggestionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuggestionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuggestionE", typeof(FlexberryEmberDemo.Suggestion));
                }
            }
            
            /// <summary>
            /// "SuggestionL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuggestionL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuggestionL", typeof(FlexberryEmberDemo.Suggestion));
                }
            }
        }
    }
}
