//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Suggestion type.
    /// </summary>
    // *** Start programmer edit section *** (SuggestionType CustomAttributes)

    // *** End programmer edit section *** (SuggestionType CustomAttributes)
    [AutoAltered()]
    [Caption("Suggestion type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SuggestionTypeE", new string[] {
            "Name as \'Название\'",
            "Moderated as \'Одобрено\'",
            "Parent as \'Родитель\'",
            "Parent.Name as \'Name\'"}, Hidden=new string[] {
            "Parent.Name"})]
    [AssociatedDetailViewAttribute("SuggestionTypeE", "LocalizedTypes", "LocalizedSuggestionTypeE", true, "", "Локализованные типы", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("SuggestionTypeE", "Parent", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("SuggestionTypeL", new string[] {
            "Name as \'Название\'",
            "Moderated as \'Одобрено\'",
            "Parent as \'Name\'"}, Hidden=new string[] {
            "Parent"})]
    public class SuggestionType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private bool fModerated;
        
        private FlexberryEmberDemo.SuggestionType fParent;
        
        private FlexberryEmberDemo.DetailArrayOfLocalizedSuggestionType fLocalizedTypes;
        
        // *** Start programmer edit section *** (SuggestionType CustomMembers)

        // *** End programmer edit section *** (SuggestionType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionType.Name CustomAttributes)

        // *** End programmer edit section *** (SuggestionType.Name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionType.Name Get start)

                // *** End programmer edit section *** (SuggestionType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (SuggestionType.Name Get end)

                // *** End programmer edit section *** (SuggestionType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionType.Name Set start)

                // *** End programmer edit section *** (SuggestionType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (SuggestionType.Name Set end)

                // *** End programmer edit section *** (SuggestionType.Name Set end)
            }
        }
        
        /// <summary>
        /// Moderated.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionType.Moderated CustomAttributes)

        // *** End programmer edit section *** (SuggestionType.Moderated CustomAttributes)
        public virtual bool Moderated
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionType.Moderated Get start)

                // *** End programmer edit section *** (SuggestionType.Moderated Get start)
                bool result = this.fModerated;
                // *** Start programmer edit section *** (SuggestionType.Moderated Get end)

                // *** End programmer edit section *** (SuggestionType.Moderated Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionType.Moderated Set start)

                // *** End programmer edit section *** (SuggestionType.Moderated Set start)
                this.fModerated = value;
                // *** Start programmer edit section *** (SuggestionType.Moderated Set end)

                // *** End programmer edit section *** (SuggestionType.Moderated Set end)
            }
        }
        
        /// <summary>
        /// Suggestion type.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionType.Parent CustomAttributes)

        // *** End programmer edit section *** (SuggestionType.Parent CustomAttributes)
        [PropertyStorage(new string[] {
                "Parent"})]
        public virtual FlexberryEmberDemo.SuggestionType Parent
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionType.Parent Get start)

                // *** End programmer edit section *** (SuggestionType.Parent Get start)
                FlexberryEmberDemo.SuggestionType result = this.fParent;
                // *** Start programmer edit section *** (SuggestionType.Parent Get end)

                // *** End programmer edit section *** (SuggestionType.Parent Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionType.Parent Set start)

                // *** End programmer edit section *** (SuggestionType.Parent Set start)
                this.fParent = value;
                // *** Start programmer edit section *** (SuggestionType.Parent Set end)

                // *** End programmer edit section *** (SuggestionType.Parent Set end)
            }
        }
        
        /// <summary>
        /// Suggestion type.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionType.LocalizedTypes CustomAttributes)

        // *** End programmer edit section *** (SuggestionType.LocalizedTypes CustomAttributes)
        public virtual FlexberryEmberDemo.DetailArrayOfLocalizedSuggestionType LocalizedTypes
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionType.LocalizedTypes Get start)

                // *** End programmer edit section *** (SuggestionType.LocalizedTypes Get start)
                if ((this.fLocalizedTypes == null))
                {
                    this.fLocalizedTypes = new FlexberryEmberDemo.DetailArrayOfLocalizedSuggestionType(this);
                }
                FlexberryEmberDemo.DetailArrayOfLocalizedSuggestionType result = this.fLocalizedTypes;
                // *** Start programmer edit section *** (SuggestionType.LocalizedTypes Get end)

                // *** End programmer edit section *** (SuggestionType.LocalizedTypes Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionType.LocalizedTypes Set start)

                // *** End programmer edit section *** (SuggestionType.LocalizedTypes Set start)
                this.fLocalizedTypes = value;
                // *** Start programmer edit section *** (SuggestionType.LocalizedTypes Set end)

                // *** End programmer edit section *** (SuggestionType.LocalizedTypes Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SuggestionTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuggestionTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuggestionTypeE", typeof(FlexberryEmberDemo.SuggestionType));
                }
            }
            
            /// <summary>
            /// "SuggestionTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuggestionTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuggestionTypeL", typeof(FlexberryEmberDemo.SuggestionType));
                }
            }
        }
    }
}
