//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Suggestion file.
    /// </summary>
    // *** Start programmer edit section *** (SuggestionFile CustomAttributes)

    // *** End programmer edit section *** (SuggestionFile CustomAttributes)
    [AutoAltered()]
    [Caption("Suggestion file")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SuggestionFileE", new string[] {
            "Order as \'Порядок\'",
            "File as \'Файл\'"})]
    public class SuggestionFile : ICSSoft.STORMNET.DataObject
    {
        
        private int fOrder;
        
        private ICSSoft.STORMNET.UserDataTypes.WebFile fFile;
        
        private FlexberryEmberDemo.Suggestion fSuggestion;
        
        // *** Start programmer edit section *** (SuggestionFile CustomMembers)

        // *** End programmer edit section *** (SuggestionFile CustomMembers)

        
        /// <summary>
        /// Order.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.Order CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.Order CustomAttributes)
        [Order()]
        public virtual int Order
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.Order Get start)

                // *** End programmer edit section *** (SuggestionFile.Order Get start)
                int result = this.fOrder;
                // *** Start programmer edit section *** (SuggestionFile.Order Get end)

                // *** End programmer edit section *** (SuggestionFile.Order Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.Order Set start)

                // *** End programmer edit section *** (SuggestionFile.Order Set start)
                this.fOrder = value;
                // *** Start programmer edit section *** (SuggestionFile.Order Set end)

                // *** End programmer edit section *** (SuggestionFile.Order Set end)
            }
        }
        
        /// <summary>
        /// File.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.File CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.File CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.WebFile File
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.File Get start)

                // *** End programmer edit section *** (SuggestionFile.File Get start)
                ICSSoft.STORMNET.UserDataTypes.WebFile result = this.fFile;
                // *** Start programmer edit section *** (SuggestionFile.File Get end)

                // *** End programmer edit section *** (SuggestionFile.File Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.File Set start)

                // *** End programmer edit section *** (SuggestionFile.File Set start)
                this.fFile = value;
                // *** Start programmer edit section *** (SuggestionFile.File Set end)

                // *** End programmer edit section *** (SuggestionFile.File Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку FlexberryEmberDemo.Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (SuggestionFile.Suggestion CustomAttributes)

        // *** End programmer edit section *** (SuggestionFile.Suggestion CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Suggestion"})]
        public virtual FlexberryEmberDemo.Suggestion Suggestion
        {
            get
            {
                // *** Start programmer edit section *** (SuggestionFile.Suggestion Get start)

                // *** End programmer edit section *** (SuggestionFile.Suggestion Get start)
                FlexberryEmberDemo.Suggestion result = this.fSuggestion;
                // *** Start programmer edit section *** (SuggestionFile.Suggestion Get end)

                // *** End programmer edit section *** (SuggestionFile.Suggestion Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SuggestionFile.Suggestion Set start)

                // *** End programmer edit section *** (SuggestionFile.Suggestion Set start)
                this.fSuggestion = value;
                // *** Start programmer edit section *** (SuggestionFile.Suggestion Set end)

                // *** End programmer edit section *** (SuggestionFile.Suggestion Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SuggestionFileE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SuggestionFileE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SuggestionFileE", typeof(FlexberryEmberDemo.SuggestionFile));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of SuggestionFile.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSuggestionFile CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSuggestionFile CustomAttributes)
    public class DetailArrayOfSuggestionFile : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (FlexberryEmberDemo.DetailArrayOfSuggestionFile members)

        // *** End programmer edit section *** (FlexberryEmberDemo.DetailArrayOfSuggestionFile members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type SuggestionFile by index.
        /// </summary>
        /// <summary>
        /// Adds object with type SuggestionFile.
        /// </summary>
        public DetailArrayOfSuggestionFile(FlexberryEmberDemo.Suggestion fSuggestion) : 
                base(typeof(SuggestionFile), ((ICSSoft.STORMNET.DataObject)(fSuggestion)))
        {
        }
        
        public FlexberryEmberDemo.SuggestionFile this[int index]
        {
            get
            {
                return ((FlexberryEmberDemo.SuggestionFile)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(FlexberryEmberDemo.SuggestionFile dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
