//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexberryEmberDemo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Vote.
    /// </summary>
    // *** Start programmer edit section *** (Vote CustomAttributes)

    // *** End programmer edit section *** (Vote CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("VoteE", new string[] {
            "VoteType as \'Тип голосования\'",
            "ApplicationUser as \'Пользователь приложения\'",
            "ApplicationUser.Name as \'Name\'"}, Hidden=new string[] {
            "ApplicationUser.Name"})]
    [MasterViewDefineAttribute("VoteE", "ApplicationUser", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Vote : ICSSoft.STORMNET.DataObject
    {
        
        private FlexberryEmberDemo.VoteType fVoteType;
        
        private FlexberryEmberDemo.ApplicationUser fApplicationUser;
        
        private FlexberryEmberDemo.Suggestion fSuggestion;
        
        // *** Start programmer edit section *** (Vote CustomMembers)

        // *** End programmer edit section *** (Vote CustomMembers)

        
        /// <summary>
        /// VoteType.
        /// </summary>
        // *** Start programmer edit section *** (Vote.VoteType CustomAttributes)

        // *** End programmer edit section *** (Vote.VoteType CustomAttributes)
        public virtual FlexberryEmberDemo.VoteType VoteType
        {
            get
            {
                // *** Start programmer edit section *** (Vote.VoteType Get start)

                // *** End programmer edit section *** (Vote.VoteType Get start)
                FlexberryEmberDemo.VoteType result = this.fVoteType;
                // *** Start programmer edit section *** (Vote.VoteType Get end)

                // *** End programmer edit section *** (Vote.VoteType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.VoteType Set start)

                // *** End programmer edit section *** (Vote.VoteType Set start)
                this.fVoteType = value;
                // *** Start programmer edit section *** (Vote.VoteType Set end)

                // *** End programmer edit section *** (Vote.VoteType Set end)
            }
        }
        
        /// <summary>
        /// Vote.
        /// </summary>
        // *** Start programmer edit section *** (Vote.ApplicationUser CustomAttributes)

        // *** End programmer edit section *** (Vote.ApplicationUser CustomAttributes)
        [PropertyStorage(new string[] {
                "ApplicationUser"})]
        [NotNull()]
        public virtual FlexberryEmberDemo.ApplicationUser ApplicationUser
        {
            get
            {
                // *** Start programmer edit section *** (Vote.ApplicationUser Get start)

                // *** End programmer edit section *** (Vote.ApplicationUser Get start)
                FlexberryEmberDemo.ApplicationUser result = this.fApplicationUser;
                // *** Start programmer edit section *** (Vote.ApplicationUser Get end)

                // *** End programmer edit section *** (Vote.ApplicationUser Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.ApplicationUser Set start)

                // *** End programmer edit section *** (Vote.ApplicationUser Set start)
                this.fApplicationUser = value;
                // *** Start programmer edit section *** (Vote.ApplicationUser Set end)

                // *** End programmer edit section *** (Vote.ApplicationUser Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку FlexberryEmberDemo.Suggestion.
        /// </summary>
        // *** Start programmer edit section *** (Vote.Suggestion CustomAttributes)

        // *** End programmer edit section *** (Vote.Suggestion CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Suggestion"})]
        public virtual FlexberryEmberDemo.Suggestion Suggestion
        {
            get
            {
                // *** Start programmer edit section *** (Vote.Suggestion Get start)

                // *** End programmer edit section *** (Vote.Suggestion Get start)
                FlexberryEmberDemo.Suggestion result = this.fSuggestion;
                // *** Start programmer edit section *** (Vote.Suggestion Get end)

                // *** End programmer edit section *** (Vote.Suggestion Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Vote.Suggestion Set start)

                // *** End programmer edit section *** (Vote.Suggestion Set start)
                this.fSuggestion = value;
                // *** Start programmer edit section *** (Vote.Suggestion Set end)

                // *** End programmer edit section *** (Vote.Suggestion Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "VoteE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VoteE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VoteE", typeof(FlexberryEmberDemo.Vote));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Vote.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfVote CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfVote CustomAttributes)
    public class DetailArrayOfVote : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (FlexberryEmberDemo.DetailArrayOfVote members)

        // *** End programmer edit section *** (FlexberryEmberDemo.DetailArrayOfVote members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Vote by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Vote.
        /// </summary>
        public DetailArrayOfVote(FlexberryEmberDemo.Suggestion fSuggestion) : 
                base(typeof(Vote), ((ICSSoft.STORMNET.DataObject)(fSuggestion)))
        {
        }
        
        public FlexberryEmberDemo.Vote this[int index]
        {
            get
            {
                return ((FlexberryEmberDemo.Vote)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(FlexberryEmberDemo.Vote dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
