//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("FlexberryEmberDemo")]
[assembly: System.Reflection.AssemblyDescription("FlexberryEmberDemo")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany(null)]
[assembly: System.Reflection.AssemblyProduct("FlexberryEmberDemo")]
[assembly: System.Reflection.AssemblyCopyright("(c) 2004-2016. NewPlatform ltd. All rights reserved.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.1")]

